# Site settings
port: 4000
title: LSystems Library
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The lsystems library can be used from the processing IDE, it just needs
  to built (maven) and manually installed
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://monkstone.github.io/LSystems"

urls:
  bugs: https://github.com/monkstone/LSystems/issues
  github: https://github.com/monkstone/LSystems/
  wiki: https://github.com/monkstone/LSystems/wiki
twitter_username: monkstoneT
github_username:  monkstone
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

include: [javadocs]
javadocs:
  blocks:
    output: true
permalink: /javadocs/:path
